source "https://rubygems.org"

gem "rails", "~> 8.1"

# Use the gem from the workspace root.
gemspec path: "../.."

gem "flat_pack", github: "bowerbird-app/flatpack", tag: "v0.1.33"
gem "minitest", "< 6"

gem "puma"

gem "sqlite3"
gem "pg" # PostgreSQL adapter for devcontainer

gem "propshaft"

gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false
