source "https://rubygems.org"

gem "rails", "~> 7.1"

# Use the gem from the workspace root
gemspec path: "../.."

gem "flat_pack", github: "bowerbird-app/flatpack", tag: "v0.1.11"
gem "flatpack-checker", github: "bowerbird-app/flatpack-checker", tag: "0.1.1"
gem "minitest", "< 6"

gem "puma"

gem "sqlite3"

gem "propshaft"

gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

# Code coverage
gem "simplecov", require: false

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false
